# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "replicant-terraform-state"
    dynamodb_table = "replicant-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
