name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Generate a Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Use the Token
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
             git config --global url."https://git:${GH_TOKEN}@github.com".insteadOf https://github.com
             git config --global user.name '${{ github.actor }}'
             git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.app-token.outputs.token }}

      - name: Build and push collector-bot image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/collector-bot:latest ./applications/collector-bot
          docker push ghcr.io/${{ github.repository_owner }}/collector-bot:latest

      - name: Build and push llm image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/llm:latest ./applications/llm
          docker push ghcr.io/${{ github.repository_owner }}/llm:latest

      - name: Build and push transcribe image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/transcribe:latest ./applications/transcribe
          docker push ghcr.io/${{ github.repository_owner }}/transcribe:latest

      - name: Build and push tts image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/tts:latest ./applications/tts
          docker push ghcr.io/${{ github.repository_owner }}/tts:latest