name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push collector-bot image
        uses: docker/build-push-action@v4
        with:
          context: ./applications/collector-bot
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/replicant/collector-bot:latest

      - name: Build and push llm image
        uses: docker/build-push-action@v4
        with:
          context: ./applications/llm
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/replicant/llm:latest

      - name: Build and push transcribe image
        uses: docker/build-push-action@v4
        with:
          context: ./applications/transcribe
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/replicant/transcribe:latest

    #   - name: Build and push tts image
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: ./applications/tts
    #       push: true
    #       tags: ghcr.io/${{ github.repository_owner }}/replicant/tts:latest