name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "applications/collector-bot/**"
      - "applications/llm/**"
      - "applications/transcribe/**"
      - "applications/tts/**"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [collector-bot, llm, transcribe, tts]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes in ${{ matrix.app }}
        id: changes
        run: |
          if git diff --quiet HEAD~1 HEAD -- applications/${{ matrix.app }}/; then
            echo "no changes"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build and push ${{ matrix.app }} image
        if: steps.changes.outputs.changes == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./applications/${{ matrix.app }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/replicant/${{ matrix.app }}:latest
          platforms: linux/arm64/v8,linux/amd64
